### ISSUE TITLE
lr scheduler?

### ISSUE THREAD

**Issue by ZPM526** [xuan611/sRGB-Real-Noise-Synthesizing#2]
Dear author, thanks for updating your code. I found that the updated lr scheduler milestone is set to 1000000 while the maximum epoch is set to 5000, which is confusing to me as the lr scheduler seems to be meaningless in this case.

**Comment by zfu006** [comment]
Hi, it means we don't update the learning rate of generators and discriminators, and the learning rates of them are set to 1e-4.

**Comment by ZPM526** [comment]
Got it, thanks for the answer.
