### ISSUE TITLE
Test data for Table 2

### ISSUE THREAD

**Issue by jamesli1618** [xuan611/sRGB-Real-Noise-Synthesizing#3]
Dear authors,

what is the test data for Table 2? Is it the SIDD validation data from this link: https://www.eecs.yorku.ca/~kamel/sidd/benchmark.php ?

Thanks!

**Comment by zfu006** [comment]
Hi, no, we test on the SIDD benchmark data, it can be also downloaded from the link you provided.

**Comment by jamesli1618** [comment]
Thanks for your reply! So the training data is the SIDD-Full Dataset or SIDD-Medium Dataset?

**Comment by zfu006** [comment]
We use the SIDD-Medium Dataset as the training set
